---
_ansible_tmp_: "/tmp/ansible"

_exec_bin_: "/usr/local/bin"
_xdg_conf_home_: "~/.config"
_xdg_data_home_: "~/.local/share"
_xdg_cache_home_: "~/.cache"


_ssh_authorized_:
  - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

__web_tz__: "{{ (lookup('pipe', 'curl -s https://ipinfo.io') | from_json).timezone }}"
__env_tz__: "{{ lookup('env', 'TZ') }}"
_time_zone_: "{{ (ansible_connection == 'local') | ternary(__web_tz__, __env_tz__) }}"


_git_: "{{ git | default(False) | bool }}"
_all_: "{{ all | default(False) | bool }}"


locale: zh_CN

git_conf:
  - name: user.name
    value: Fly me to the moon
  - name: user.email
    value: git@bigly.dog
  - name: diff.algorithm
    value: minimal
