---

_ssh_authorized_:
  - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

__web_tz__: "{{ (lookup('pipe', 'curl -s https://ipinfo.io') | from_json).timezone }}"
__env_tz__: "{{ lookup('env', 'TZ') }}"
_time_zone_: "{{ (ansible_connection == 'local') | ternary(__web_tz__, __env_tz__) }}"

_all_: "{{ all | default(False) | bool }}"
_reset_: "{{ reset | default(False) | bool }}"


git_conf:
  - name: user.name
    value: Fly me to the moon
  - name: user.email
    value: git@bigly.dog
