---
_exec_bin_: "/usr/local/bin"
_xdg_conf_home_: "~/.config"
_xdg_data_home_: "~/.local/share"
_xdg_cache_home_: "~/.cache"

_ssh_authorized_:
  - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

_time_zone_: "{{ lookup('env', 'TZ') | default(tz) }}"

_git_: "{{ git | default(False) | bool }}"
_all_: "{{ all | default(False) | bool }}"

locale: zh_CN
