---

- hosts: ubuntu
  become: yes

  vars:
    git_name: Fly me to the moon
    git_email: git@bigly.dog

    sync_all: yes
    from_scratch: no

  tasks:
    - assert:
        that: ansible_distribution != 'MacOSX'

    - import_role:
        name: ubuntu
