---

- import_tasks: install_deps.yml
- import_tasks: clone_repos.yml

- import_tasks: link_files.yml
  when: ansible_connection == "local"

- import_tasks: copy_files.yml
  when: ansible_connection != "local"
