---
- name: add ssh pub key
  loop: "{{ _ssh_authorized_ }}"
  ansible.builtin.authorized_key:
    user: root
    key: "{{ item }}"

- name: set root_pw
  when: root_pw is defined
  ansible.builtin.user:
    name: root
    password: "{{ root_pw | password_hash('sha512') }}"

- name: disable password login
  when: root_pw is not defined
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
  register: __root_ssh

- name: enable root login
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PermitRootLogin yes"
  register: __root_ssh

- name: restart sshd
  when: __root_ssh.changed
  ansible.builtin.systemd:
    name: sshd
    state: restarted
