---

- name: sync files
  loop: "{{ target_files }}"
  synchronize:
    group: False
    owner: False
    delete: "{{ item.delete | default(False) }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
