---

nano_path: /usr/share/nano

target_files:
  - src: "zsh/custom_linux/"
    dest: "{{ _omz_dir_ }}/custom/"


_core_utils:
  - sudo
  - snapd
  - python3-pip
  - zsh
  - mosh
  - trash-cli
  - rsync
  - curl
  - wget
  - grep
  - jq
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - pv
  - ncdu
  - iperf3


_nice_things:
  # - exa
  # - bat
  # - fzf
  # - fd-find
  # - ripgrep
  # - peco
  - tldr


_fun_things:
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet
  - libaa-bin #aafire
  - bb


snap_packages:
  - name: micro
    classic: True
  - name: yq


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"


apt_packages: "{{ _core_utils + _nice_things + _fun_things }}"


apt_deb_packages:
  # Next version of LTS should have these #
  - "https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb"
  - "http://archive.ubuntu.com/ubuntu/pool/universe/f/fzf/fzf_0.17.5-2_amd64.deb"
  - "https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb"
  - "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb"
  # Required Deb #
  - "https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb"


target_downloads:
  - src: "https://github.com/tsl0922/ttyd/releases/download/1.5.2/ttyd_linux.x86_64"
    dest: "/usr/local/bin/ttyd"


target_archives:
  - src: "https://github.com/peco/peco/releases/download/v0.5.7/peco_linux_amd64.tar.gz"
    dest: "/tmp/peco"
  - src: "https://github.com/Canop/broot/releases/download/v0.12.0/release.zip"
    dest: "/tmp/broot"


target_mods:
  - path: "/usr/local/bin/ttyd"
    mode: "775"
  - path: "/tmp/peco"
    mode: "775"
  - path: "/tmp/broot"
    mode: "775"


target_moves:
  - src: "/tmp/peco/peco"
    dest: "/usr/local/bin/peco"
  - src: "/tmp/broot/x86_64-linux/broot"
    dest: "/usr/local/bin/broot"
