---
nano_path: /usr/share/nano


target_templates:
  - src: "etc/locale.j2"
    dest: "/etc/default/locale"


_languages:
  - language-pack-zh-hans


_core_utils:
  - man
  - sudo
  - locales
  - openssh-server
  - mosh
  - tmux
  - rsync
  - curl
  - wget
  - grep
  - jq
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - dstat
  - pv
  - socat
  - sysstat
  - ncdu
  - iperf3
  - unzip


_editors:
  - neovim
  - emacs
  - lazygit


_nice_things:
  - bat
  - fzf
  - fd-find
  # - ripgrep
  # apt install -o Dpkg::Options::="--force-overwrite" ripgrep
  # TODO: https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517


_fun_things:
  - termshark
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - figlet
  - libaa-bin #aafire
  - bb


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"
  - "ppa:lazygit-team/release"
  - "ppa:neovim-ppa/unstable"


apt_packages: "{{ _languages + _core_utils + _editors + _nice_things + _fun_things }}"


apt_deb_packages:
  - "https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb"
  - "https://github.com/dandavison/delta/releases/download/0.1.1/git-delta_0.1.1_amd64.deb"


target_downloads: []


target_archives:
  - src: "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
    dest: "{{ _ansible_tmp_ }}"
  - src: "https://github.com/chmln/sd/releases/download/v0.7.5/sd.0.7.5-.x86_64-unknown-linux-gnu.zip"
    dest: "{{ _ansible_tmp_  }}"
  - src: "https://github.com/XAMPPRocky/tokei/releases/download/v11.1.1/tokei-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ _exec_bin_ }}"


target_remote_copy:
  - src: "{{ _ansible_tmp_ }}/exa-linux-x86_64"
    dest: "{{ _exec_bin_ }}/exa"
  - src: "{{ _ansible_tmp_ }}/b/x86_64-unknown-linux-gnu/release/sd"
    dest: "{{ _exec_bin_ }}/sd"


target_links:
  - src: "/bin/batcat"
    dest: "/usr/local/bin/bat"
  - src: "/bin/fdfind"
    dest: "/usr/local/bin/fd"


target_mods:
  - src: "{{ _exec_bin_ }}/exa"
    mode: "+x"
  - src: "{{ _exec_bin_ }}/sd"
    mode: "+x"

