---

nano_path: /usr/share/nano

target_files:
  - src: "zsh/custom_linux/"
    dest: "{{ _omz_dir_ }}/custom/"


_core_utils:
  - snapd
  - python3-pip
  - zsh
  - mosh
  - python3-pip
  - python-pip
  - rsync
  - curl
  - wget
  - grep
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - pv


_nice_things:
  # - exa
  # - bat
  # - fzf
  # - fd-find
  # - ripgrep
  - autojump
  - tldr

_fun_things:
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet


snap_packages:
  - name: micro
    classic: True


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ __release_version__ }} partner"

apt_packages: "{{ _core_utils + _nice_things + _fun_things }}"


