---
nano_path: /usr/share/nano


target_templates:
  - src: "templates/ubuntu/"
    dest: "/"


_languages:
  - language-pack-zh-hans


_core_utils:
  - earlyoom
  - man
  - sudo
  - locales
  - openssh-server
  - mosh
  - tmux
  - rsync
  - curl
  - wget
  - grep
  - jq
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - dstat
  - pv
  - socat
  - sysstat
  - ncdu
  - iperf3
  - unzip


_editors:
  - neovim
  - lazygit


_nice_things:
  - bat
  - fzf
  - fd-find
  # - ripgrep
  # apt install -o Dpkg::Options::="--force-overwrite" ripgrep
  # TODO: https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517


_fun_things:
  - termshark
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - figlet
  - libaa-bin #aafire
  - bb


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"
  - "ppa:lazygit-team/release"
  - "ppa:neovim-ppa/unstable"


apt_packages: "{{ _languages + _core_utils + _editors + _nice_things + _fun_things }}"


apt_deb_packages:
  - "https://github.com/dandavison/delta/releases/download/0.4.3/git-delta_0.4.3_amd64.deb"
  - "https://github.com/sharkdp/hyperfine/releases/download/v1.10.0/hyperfine_1.10.0_amd64.deb"
  - "https://github.com/sharkdp/pastel/releases/download/v0.8.0/pastel_0.8.0_amd64.deb"
  - "https://github.com/muesli/duf/releases/download/v0.5.0/duf_0.5.0_linux_amd64.deb"
  - "https://github.com/ms-jpq/sad/releases/download/ci_0.4.7_2020-08-06_07-03/x86_64-unknown-linux-gnu.deb"


target_downloads: []


target_archives:
  - src: "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
    dest: "{{ _ansible_tmp_ }}"
  - src: "https://github.com/XAMPPRocky/tokei/releases/download/v12.0.3/tokei-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ _exec_bin_ }}"
  - src: "https://github.com/simeji/jid/releases/download/v0.7.6/jid_linux_amd64.zip"
    dest: "{{ _exec_bin_ }}"


target_remote_copy:
  - src: "{{ _ansible_tmp_ }}/exa-linux-x86_64"
    dest: "{{ _exec_bin_ }}/exa"


target_links: []


target_mods:
  - src: "{{ _exec_bin_ }}/exa"
    mode: "+x"
