---

_ansible_tmp_: "/tmp/ansible"
_exec_bin_: "/usr/local/bin"

nano_path: /usr/share/nano

target_dirs:
  - "{{ _ansible_tmp_ }}"

target_files:
  - src: "zsh/custom_linux/"
    dest: "{{ _omz_dir_ }}/custom/"

target_templates:
  - src: "etc/locale.j2"
    dest: "/etc/default/locale"

_languages:
  - language-pack-zh-hans

_core_utils:
  - sudo
  - mosh
  - tmux
  - emacs
  - socat
  - trash-cli
  - rsync
  - curl
  - wget
  - grep
  - jq
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - dstat
  - pv
  - sysstat
  - ncdu
  - iperf3
  - unzip


_nice_things:
  # - exa
  # - bat
  # - fzf
  # - fd-find
  # - ripgrep
  - httpie
  - tldr


_fun_things:
  # - termshark
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet
  - libaa-bin #aafire
  - bb


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"


apt_packages: "{{ _languages + _core_utils + _nice_things + _fun_things }}"


apt_deb_packages:
  # Next version of LTS should have these #
  - "https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb"
  - "http://archive.ubuntu.com/ubuntu/pool/universe/f/fzf/fzf_0.17.5-2_amd64.deb"
  - "https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb"
  - "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb"
  # Required Deb #
  - "https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb"


target_downloads:
  - src: "https://github.com/tsl0922/ttyd/releases/download/1.5.2/ttyd_linux.x86_64"
    dest: "{{ _exec_bin_ }}/ttyd"
  - src: "https://github.com/mikefarah/yq/releases/download/3.1.0/yq_linux_amd64"
    dest: "{{ _exec_bin_ }}/yq"


target_archives:
  - src: "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
    dest: "{{ _ansible_tmp_ }}"


target_remote_copy:
  - src: "{{ _ansible_tmp_ }}/exa-linux-x86_64"
    dest: "{{ _exec_bin_ }}/exa"


target_mods:
  - path: "{{ _exec_bin_ }}/exa"
    mode: "775"
  - path: "{{ _exec_bin_ }}/ttyd"
    mode: "775"
  - path: "{{ _exec_bin_ }}/yq"
    mode: "775"
