---

_ansible_tmp_: "/tmp/ansible"
_exec_bin_: "/usr/local/bin"

nano_path: /usr/share/nano

target_dirs:
  - "{{ _ansible_tmp_ }}"

target_files:
  - src: "zsh/linux/"
    dest: "{{ _zsh_dir_ }}/distro"
    delete: True

target_templates:
  - src: "etc/locale.j2"
    dest: "/etc/default/locale"

_languages:
  - language-pack-zh-hans

_core_utils:
  - sudo
  - mosh
  - tmux
  - socat
  - trash-cli
  - rsync
  - curl
  - wget
  - grep
  - jq
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  - dstat
  - pv
  - sysstat
  - ncdu
  - iperf3
  - unzip


_editors:
  - neovim
  - emacs
  - lazygit
  - diff-so-fancy


_nice_things:
  - bat
  - fzf
  - fd-find
  # - ripgrep
  # apt install -o Dpkg::Options::="--force-overwrite" ripgrep
  # TODO: https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517


_fun_things:
  - termshark
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet
  - libaa-bin #aafire
  - bb


apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner"
  - "ppa:lazygit-team/release"


apt_packages: "{{ _languages + _core_utils + _editors + _nice_things + _fun_things }}"


apt_deb_packages:
  - "https://github.com/cjbassi/gotop/releases/download/3.0.0/gotop_3.0.0_linux_amd64.deb"


target_downloads:
  - src: "https://github.com/tsl0922/ttyd/releases/download/1.6.0/ttyd_linux.x86_64"
    dest: "{{ _exec_bin_ }}/ttyd"


target_archives:
  - src: "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
    dest: "{{ _ansible_tmp_ }}"
  - src: "https://github.com/chmln/sd/releases/download/v0.7.4/sd-0.7.4.x86_64-unknown-linux-gnu.zip"
    dest: "{{ _ansible_tmp_  }}"


target_remote_copy:
  - src: "{{ _ansible_tmp_ }}/exa-linux-x86_64"
    dest: "{{ _exec_bin_ }}/exa"
  - src: "{{ _ansible_tmp_ }}/b/x86_64-unknown-linux-gnu/release/sd"
    dest: "{{ _exec_bin_ }}/sd"


target_links:
  - src: "/bin/batcat"
    dest: "/usr/local/bin/bat"
  - src: "/bin/fdfind"
    dest: "/usr/local/bin/fd"


target_mods:
  - path: "{{ _exec_bin_ }}/exa"
    mode: "775"
  - path: "{{ _exec_bin_ }}/sd"
    mode: "775"
  - path: "{{ _exec_bin_ }}/ttyd"
    mode: "775"
