---

_nano_path: /usr/share/nano

_additional_files:
  - src: "../ubuntu/files/zsh/custom/"
    dest: "{{ _omz_dir_ }}/custom/"

_additional_python_lbs:
  - name: setuptools
    version: pip

_core_utils:
  - zsh
  - python3-pip
  - python-pip
  - rsync
  - curl
  - wget
  - grep
  - nano
  - htop
  - nmap
  - tree

_nice_things:
  - thefuck
  - tldr

_fun_things:
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet

_apt_repos: []

_apt_packages: "{{ _core_utils + _nice_things + _fun_things }}"


