---

_nano_path: /usr/share/nano

_additional_files:
  - src: "zsh/custom_linux/"
    dest: "{{ _omz_dir_ }}/custom/"

python_packages:
  - name: setuptools
    version: pip3

_core_utils:
  - zsh
  - python3-pip
  - python-pip
  - rsync
  - curl
  - wget
  - grep
  - nano
  - nmap
  - tree
  - psmisc
  - htop
  - iotop
  - iftop
  # - fd-find
  # - bat
  # - exa
  # - fzf

_nice_things:
  - thefuck
  - tldr

_fun_things:
  - neofetch
  - sl
  - cmatrix
  - nyancat
  - cowsay
  - lolcat
  - figlet

gpg_keys: []

apt_repos:
  - "deb http://archive.canonical.com/ubuntu {{ __release_version__ }} partner"

apt_packages: "{{ _core_utils + _nice_things + _fun_things }}"


