---

- import_tasks: homebrew_repos.yml
  when: _all_

- import_tasks: homebrew.yml
  when: _all_

- import_tasks: pip.yml
  when: _all_

- import_tasks: mkdir.yml

- import_tasks: sync.yml

- import_tasks: template.yml

- import_tasks: link.yml
