# Configuration documentation is available at https://dystroy.org/broot


#################### ########### ####################
#################### Skin Region ####################
#################### ########### ####################

[[verbs]]
invocation = ":quit"
execution = ":quit"
key = "ctrl-c"


[[verbs]]
invocation = ":refresh"
execution = ":refresh"
key = "ctrl-r"


[[verbs]]
invocation = ":page_up"
execution = ":page_up"
key = "ctrl-z"

[[verbs]]
invocation = ":page_down"
execution = ":page_down"
key = "ctrl-x"


[[verbs]]
invocation = ":toggle_hidden"
execution = ":toggle_hidden"
key = "ctrl-h"


[[verbs]]
invocation = ":toggle_files"
execution = ":toggle_files"
key = "ctrl-f"


[[verbs]]
invocation = ":toggle_sizes"
execution = ":toggle_sizes"
shortcut = "s"
key = "ctrl-s"


[[verbs]]
invocation = ":toggle_dates"
execution = ":toggle_dates"
shortcut = "d"
key = "ctrl-d"


[[verbs]]
invocation = ":toggle_perm"
execution = ":toggle_perm"
shortcut = "p"
key = "ctrl-p"


[[verbs]]
invocation = ":focus_user_home"
execution = ":focus_user_home"
shortcut = "home"


[[verbs]]
invocation = ":focus_root"
execution = ":focus_root"
shortcut = "root"


[[verbs]]
invocation = ":open_stay"
execution = ":open_stay"
shortcut = "os"


[[verbs]]
invocation = ":open_leave"
execution = ":open_leave"
shortcut = "ol"


[[verbs]]
invocation = "open"
execution = "open {file}"
shortcut = "o"
key = "ctrl-o"


[[verbs]]
invocation = "trash"
execution = "trash {file}"
shortcut = "trash"


[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
shortcut = "n"


[[verbs]]
invocation = "edit"
execution = "$EDITOR {file}"
shortcut = "e"
key = "ctrl-e"


#################### ########### ####################
#################### Skin Region ####################
#################### ########### ####################

[skin]
default = "gray(2) gray(23)"
tree = "gray(17) none"
file = "gray(1) none"
directory = "ansi(20) none bold"
exe = "ansi(178) none"
link = "Magenta none"
pruning = "gray(5) none Italic"
perm__ = "gray(19) None"
perm_r = "ansi(92) None"
perm_w = "ansi(192) None"
perm_x = "ansi(69) None"
selected_line = "none gray(20)"
char_match = "ansi(28) none"
file_error = "Red none"
flag_label = "gray(16) none"
flag_value = "ansi(202) none bold"
input = "ansi(0) none"
status_error = "ansi(196) gray(22)"
status_job = "ansi(220) gray(18)"
status_normal = "gray(2) gray(22)"
status_italic = "ansi(202) gray(22)"
status_bold = "ansi(202) gray(22) bold"
status_code = "ansi(17) gray(22)"
status_ellipsis = "gray(1) white"
scrollbar_track = "gray(20) none"
scrollbar_thumb = "ansi(238) none"
help_paragraph = "gray(2) none"
help_bold = "ansi(202) none bold"
help_italic = "ansi(202) none italic"
help_code = "gray(5) gray(22)"
help_headers = "ansi(202) none"
