---
- name: add docker gpg Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: update apt and install docker-ce
  apt:
    update_cache: yes
    state: latest
    name: "{{ docker-dependencies }}"

- name: install python docker module
  pip:
    executable: pip3
    name: "{{ python-libs }}"
