---

- import_tasks: _package.yml
  when: sync_all

- import_tasks: _remove_fs.yml
  when: from_scratch

- import_tasks: _git_clone.yml
  when: sync_all or from_scratch

- import_tasks: copy.yml

- import_tasks: templates.yml
