---
- import_tasks: packages.yml
  when: _all_

- import_tasks: git.yml
  when: _git_ or _all_

- import_tasks: sync.yml

- import_tasks: template.yml

- import_tasks: touch.yml

- import_tasks: git_conf.yml

- import_tasks: lineinfile.yml

- import_tasks: link.yml
