---

- import_tasks: packages.yml
  when: sync_all

- import_tasks: remove_fs.yml
  when: from_scratch

- import_tasks: git.yml
  when: sync_all or from_scratch

- import_tasks: copy.yml

- import_tasks: templates.yml
