---

- import_tasks: packages.yml
  when: sync_all

- import_tasks: git_conf.yml

- import_tasks: remove_fs.yml
  when: from_scratch

- import_tasks: git.yml
  when: sync_all or from_scratch

- import_tasks: mkdir.yml

- import_tasks: touch.yml

- import_tasks: sync.yml

- import_tasks: template.yml
