---

## GLOBAL ##
_user_dir_: "{{ '~' if ansible_distribution == 'MacOSX' else '/root' }}"
_omz_dir_: "{{ _user_dir_ }}/.oh-my-zsh"
_nano_backup_dir_: "{{ _user_dir_ }}/.nano_backup"
## GLOBAL ##


# INPUT #
nano_path: ""
sync_all: yes
from_scratch: yes
additional_files: []
additional_templates: []
# INPUT #


packages:
  - git
  - zsh
  - python3

python_packages:
  - name: setuptools
    version: pip3
  - name: pygments
    version: pip3


git_repos:
  - src: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ _omz_dir_ }}"

  - src: "https://github.com/romkatv/powerlevel10k"
    dest: "{{ _omz_dir_ }}/themes/powerlevel10k"

  - src: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "{{ _omz_dir_ }}/plugins/zsh-syntax-highlighting"

  - src: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ _omz_dir_ }}/plugins/zsh-autosuggestions"

  - src: "https://github.com/zsh-users/zsh-completions"
    dest: "{{ _omz_dir_ }}/plugins/zsh-completions"

  - src: "https://github.com/zsh-users/zsh-history-substring-search"
    dest: "{{ _omz_dir_ }}/plugins/zsh-history-substring-search"

  - src: "https://github.com/syl20bnr/spacemacs"
    dest: "{{ _user_dir_ }}/.emacs.d"

_shared_files:
  - src: "zsh/rc.zsh"
    dest: "{{ _user_dir_ }}/.zshrc"

  - src: "zsh/.p10k.zsh"
    dest: "{{ _user_dir_ }}/.p10k.zsh"

  - src: "zsh/custom/"
    dest: "{{ _omz_dir_ }}/custom/"

  - src: "micro/"
    dest: "{{ _user_dir_ }}/.config/micro/"

  - src: ".ansible.cfg"
    dest: "{{ _user_dir_ }}/.ansible.cfg"


target_dirs:
  - "{{ _nano_backup_dir_ }}"

target_files: "{{ _shared_files + additional_files }}"


_shared_templates:
  - src: ".nanorc.j2"
    dest: "{{ _user_dir_ }}/.nanorc"

target_templates: "{{ _shared_templates + additional_templates }}"
