---

## GLOBAL ##
_zsh_dir_: "{{ _conf_home_ }}/zsh"
_omz_dir_: "{{ _zsh_dir_  }}/oh-my-zsh"
## GLOBAL ##


packages:
  - git
  - zsh


git_repos:
  - src: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ _omz_dir_ }}"

  - src: "https://github.com/romkatv/powerlevel10k"
    dest: "{{ _zsh_dir_ }}/powerlevel10k"

  - src: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "{{ _zsh_dir_ }}/zsh-syntax-highlighting"

  - src: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ _zsh_dir_ }}/zsh-autosuggestions"

  - src: "https://github.com/zsh-users/zsh-completions"
    dest: "{{ _zsh_dir_ }}/zsh-completions"

  - src: "https://github.com/zsh-users/zsh-history-substring-search"
    dest: "{{ _zsh_dir_ }}/zsh-history-substring-search"

  - src: "https://github.com/junegunn/fzf.git"
    dest: "{{ _zsh_dir_  }}/fzf"

  - src: "https://github.com/Aloxaf/fzf-tab.git"
    dest: "{{ _zsh_dir_ }}/fzf-tab"

  - src: "https://github.com/rupa/z.git"
    dest: "{{ _zsh_dir_ }}/z"

  - src: "https://github.com/seebi/dircolors-solarized"
    dest: "{{ _zsh_dir_ }}/dircolors-solarized"

  - src: "https://github.com/dylanaraps/fff"
    dest: "{{ _zsh_dir_ }}/fff"

  - src: "https://github.com/LuRsT/hr.git"
    dest: "{{ _zsh_dir_ }}/hr"

  - src: "https://github.com/so-fancy/diff-so-fancy.git"
    dest: "{{ _zsh_dir_ }}/diff-so-fancy"

  - src: "https://github.com/cyproterone/tmux.git"
    dest: "{{ _conf_home_  }}/tmux"

  - src: "https://github.com/tmux-plugins/tpm"
    dest: "{{ _conf_home_ }}/tmux/plugins/tpm"

  - src: "https://github.com/cyproterone/vim.git"
    dest: "{{ _conf_home_ }}/nvim"

  - src: "https://github.com/cyproterone/emacs.d.git"
    dest: "{{ _conf_home_ }}/emacs.d"

  - src: "https://github.com/cyproterone/ranger.git"
    dest: "{{ _conf_home_ }}/ranger"

  - src: "https://github.com/pyenv/pyenv.git"
    dest: "{{ _conf_home_ }}/pyenv"

  - src: "https://github.com/nodenv/nodenv.git"
    dest: "{{ _conf_home_ }}/nodenv"

  - src: "https://github.com/nodenv/node-build.git"
    dest: "{{ _conf_home_ }}/nodenv/plugins/node-build"

  - src: "https://github.com/rbenv/rbenv.git"
    dest: "{{ _conf_home_ }}/rbenv"

  - src: "https://github.com/rbenv/ruby-build.git"
    dest: "{{ _conf_home_ }}/rbenv/plugins/ruby-build"


target_dirs:
  - "{{ _ansible_tmp_ }}"
  - "{{ _conf_home_ }}"
  - "{{ _zsh_dir_ }}"
  - "{{ _zsh_dir_ }}/intrinsic"
  - "{{ _local_bin_ }}"
  - "{{ _conf_home_ }}/scripts"
  - "~/.ssh"
  - "~/.cache"
  - "~/.cache/zsh"


target_touches:
  - "~/.ssh/config"
  - "~/.cache/zz"


target_files:
  - src: "config/"
    dest: "~/.config/"

  - src: "zsh/shared/"
    dest: "{{ _zsh_dir_ }}/shared"
    delete: True

  - src: "zsh/apriori/"
    dest: "{{ _zsh_dir_ }}/apriori"
    delete: True

  - src: "zsh/plugins/"
    dest: "{{ _zsh_dir_ }}/plugins"
    delete: True

  - src: "scripts/"
    dest: "{{ _conf_home_ }}/scripts"
    delete: True


target_templates:
  - src: "zsh/locale.zsh.j2"
    dest: "{{ _zsh_dir_ }}/intrinsic/locale.zsh"

  - src: "zsh/tz.zsh.j2"
    dest: "{{ _zsh_dir_ }}/intrinsic/tz.zsh"

  - src: ".nanorc.j2"
    dest: "~/.nanorc"


target_lines:
  - file: "~/.ssh/config"
    line: "ServerAliveInterval 1"
  - file: "~/.ssh/config"
    line: "ServerAliveCountMax 5"


target_links:
  - src: "{{ _conf_home_ }}/zsh/.zshenv"
    dest: "~/.zshenv"

  - src: "{{ _conf_home_ }}/tmux/entry.conf"
    dest: "~/.tmux.conf"

  - src: "{{ _conf_home_ }}/emacs.d"
    dest: "~/.emacs.d"
