---

- name: "add gpg key {{ _gpg_keys }}"
  become: yes
  loop: "{{ _gpg_keys }}"
  apt_key:
    url: "{{ item }}"

- name: "add apt repo {{ _apt_repos }} "
  become: yes
  loop: "{{ _apt_repos }}"
  apt_repository:
    repo: "{{ item }}"
  register: __apt_repo

- name: "apt update"
  become: yes
  apt:
    update_cache: yes
  when: __apt_repo.changed
