---

- name: set default shell
  user:
    name: root
    shell: /bin/zsh


- name: add ssh pub key
  loop: "{{ __ssh_authorized__ }}"
  authorized_key:
    user: root
    key: "{{ item }}"


- name: enable root login
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PermitRootLogin yes"
  register: __root_ssh


- name: restart sshd
  when: __root_ssh.changed
  systemd:
    name: sshd
    state: restarted
