---

- import_tasks: shell.yml

- import_tasks: copy.yml

- import_tasks: apt_repo.yml
  when: sync_all

- import_tasks: apt.yml
  when: sync_all

- import_tasks: apt_deb.yml
  when: sync_all

- import_tasks: snap.yml
  when: sync_all

- import_tasks: pip.yml
  when: sync_all
