---

- import_tasks: shell.yml

- import_tasks: apt_repo.yml
  when: _all_

- import_tasks: apt.yml
  when: _all_

- import_tasks: apt_deb.yml
  when: _all_

- import_tasks: snap.yml
  when: _all_

- import_tasks: pip.yml
  when: _all_

- import_tasks: sync.yml
