---
- name: install classic snaps
  community.general.snap:
    name: "{{ snap_packages.classic | default([]) }}"
    classic: True

- name: install snaps
  community.general.snap:
    name: "{{ snap_packages.new | default([]) }}"
    classic: True
