---

- hosts: localhost
  connection: local
  gather_facts: no

  # Change quick_sync -> yes for full sync
  vars:
    quick_sync: yes

  roles:
    - role: shell_macos
    - role: macos_dev
      when: not quick_sync
